PBD_Library_Django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('PBD_library.urls')),
    path('admin/', admin.site.urls),
]

PBD_library/urls.py
from django.urls import path

from . import views


app_name = 'PBD_library'
urlpatterns = [
                path('', views.index, name='index'),
                path('books_list', views.books_list, name='books_list'),
                path('book/<int:book_id>', views.book_detail, name='book_detail'),
                path('users_list', views.users_list, name='users_list'),
                path('user/<int:user_id>', views.user_detail, name='user_detail'),

]

PBD_library/models.py
from django.db import models
from django.utils import timezone


class Address(models.Model):
    street = models.CharField(max_length=100)
    number = models.PositiveIntegerField()
    neighborhood = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    country = models.CharField(max_length=20)

class Person(models.Model):
    name = models.CharField(unique=True, max_length=100)
    address = models.OneToOneField(Address, on_delete=models.DO_NOTHING, null=True, blank=True)
    telephone = models.CharField(max_length=20)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name

class Author(Person):
    CPF = models.CharField(max_length=14, unique=True)
    pass

class Publisher(Person):
    CNPJ = models.CharField(max_length=18, unique=True)

class Book(models.Model):
    name = models.CharField(max_length=100, unique=True)
    keywords = models.TextField(max_length=100)
    quantity = models.PositiveIntegerField(default=0)
    authors = models.ManyToManyField(Author, related_name='books')
    publisher = models.ForeignKey(Publisher, on_delete=models.DO_NOTHING, related_name='books')

    def __str__(self):
        return self.name

class Copy(models.Model):
    lent = models.BooleanField(default=False)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='copies')

    def __str__(self):
        if self.lent:
            lent = ' -- [Emprestado]'
        else:
            lent = ' -- [Disponível]'

        return self.book.name + lent

class User(Person):
    student = models.BooleanField()


class Loan(models.Model):
    loan_date = models.DateField(default=timezone.now)
    return_date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='loans')
    copy = models.ForeignKey(Copy, on_delete=models.CASCADE, related_name='loans')

PBD_library/forms.py
from django import forms
from .models import *

class BookAdminForm(forms.ModelForm):
    quantity = forms.IntegerField(disabled=True, initial=0)
    class Meta:
        model = Book
        fields = '__all__'

class CopyAdminForm(forms.ModelForm):
    class Meta:
        model = Copy
        fields = '__all__'

    def clean(self):
        super(CopyAdminForm, self).clean()
        book = self.cleaned_data['book']
        book.quantity += 1
        book.save()

PBD_library/views.py
from django.shortcuts import render
from .models import *
from .forms import *

# Create your views here.

def index(request):
    return render(request, 'PBD_library/index.html')

def books_list(request):
    books = Book.objects.all()

    return render(request, 'PBD_library/books_list.html', {'books': books})

def book_detail(request, book_id):
    book = Book.objects.get(pk=book_id)
    authors = book.authors.all()
    copies = book.copies.all()

    return render(request, 'PBD_library/book_detail.html', {'book':book, 'authors':authors, 'copies':copies})

def users_list(request):
    users = User.objects.all()

    return render(request, 'PBD_library/users_list.html', {'users':users})

def user_detail(request, user_id):
    user = User.objects.get(pk=user_id)
    loans = user.loans.all()
    copies = []
    for loan in loans:
        copies.append(loan.copy)

    return render(request, 'PBD_library/user_detail.html', {'user': user, 'loans': loans, 'copies': copies})

PBD_library/templates/PBD_library/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
    <h1>{{ book.name }}</h1>
    <ul>

    <li>Autor: {% for author in authors %}{{ author.name }}, {% endfor %}</li>

    <li>Editora: {{ book.publisher.name }}</li>

    <li>Palavras-chave: {{ book.keywords }}</li>

    <li>Quantidade: {{ book.quantity }}</li>

    </ul>

<h3>Emprestimos</h3>
{% for copy in copies.all    %}
    {{ copy }}

{% endfor %}
</body>
</html>

PBD_library/templates/PBD_library/books_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de livros</title>
</head>
<body>
    <h1>Lista de livros</h1>
    <ul>

    {% for book in books %}
        <li><a href=" {% url 'PBD_library:book_detail' book.id %}">{{ book.name }}</a></li>
    {% endfor %}
    </ul>
</body>
</html>

PBD_library/templates/PBD_library/index.html
<h1>PBD LIBRARY</h1>

<ul>
    <li><a href=" {% url  'PBD_library:books_list' %}">Livros</a></li>
    <li><a href=" {% url  'PBD_library:users_list' %}">Usuários</a></li>
    <li><a href="admin/">admin</a></li>
</ul>

PBD_library/templates/PBD_library/user_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1>{{ user.name }}</h1>
<ul>
    <li>Telefone: {{ user.telephone }}</li>
    <li>Student: {{ user.student }}</li>
<h3>Emprestimos</h3>
    <ul>
        {% for loan in loans %}
            <li>{{ loan.copy.book.name }}</li>
        {% endfor %}
    </ul>
</ul>
</body>
</html>

PBD_library/templates/PBD_library/users_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de usuários</title>
</head>
<body>
    <h1>Lista de usuários</h1>
    <ul>

    {% for user in users %}
                <li><a href=" {% url 'PBD_library:user_detail' user.id %}">{{ user.name }}</a></li>

    {% endfor %}
    </ul>
</body>
</html>